# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.moder import moder_pb2 as moder_dot_moder__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in moder/moder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductsStub(object):
    """Products модерация товаров
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextProduct = channel.unary_unary(
                '/product_moderation.Products/GetNextProduct',
                request_serializer=moder_dot_moder__pb2.GetNextProductRequest.SerializeToString,
                response_deserializer=moder_dot_moder__pb2.Product.FromString,
                _registered_method=True)
        self.AcceptProduct = channel.unary_unary(
                '/product_moderation.Products/AcceptProduct',
                request_serializer=moder_dot_moder__pb2.AcceptDescision.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.DeclineProduct = channel.unary_unary(
                '/product_moderation.Products/DeclineProduct',
                request_serializer=moder_dot_moder__pb2.DeclineDescision.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ProductsServicer(object):
    """Products модерация товаров
    """

    def GetNextProduct(self, request, context):
        """GetNextProduct возвращает следующий товар на модерацию
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptProduct(self, request, context):
        """AcceptProduct одобрить размещение товара в каталоге пользователей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclineProduct(self, request, context):
        """DeclineProduct одобрить размещение товара в каталоге пользователей
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextProduct,
                    request_deserializer=moder_dot_moder__pb2.GetNextProductRequest.FromString,
                    response_serializer=moder_dot_moder__pb2.Product.SerializeToString,
            ),
            'AcceptProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptProduct,
                    request_deserializer=moder_dot_moder__pb2.AcceptDescision.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'DeclineProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclineProduct,
                    request_deserializer=moder_dot_moder__pb2.DeclineDescision.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product_moderation.Products', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product_moderation.Products', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Products(object):
    """Products модерация товаров
    """

    @staticmethod
    def GetNextProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_moderation.Products/GetNextProduct',
            moder_dot_moder__pb2.GetNextProductRequest.SerializeToString,
            moder_dot_moder__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_moderation.Products/AcceptProduct',
            moder_dot_moder__pb2.AcceptDescision.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclineProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product_moderation.Products/DeclineProduct',
            moder_dot_moder__pb2.DeclineDescision.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
