import json
from datetime import datetime
from uuid import uuid4

categories = {
    # Корневые категории
    "electronics-and-peripherals": {"name": "Электроника и периферия"},
    "home-appliances-and-personal-care": {"name": "Бытовая техника и уход"},
    "clothing-footwear-and-accessories": {"name": "Одежда, обувь и аксессуары"},
    "furniture-and-home-textiles": {"name": "Мебель и домашний текстиль"},
    "repair-and-tools": {"name": "Ремонт и инструменты"},
    "pet-supplies": {"name": "Зоотовары"},
    "baby-and-kids-products": {"name": "Детские товары"},
    "sports-and-outdoors": {"name": "Спорт и активный отдых"},

    # Электроника и периферия
    "smartphones": {"name": "Смартфоны"},
    "laptops": {"name": "Ноутбуки"},
    "headphones": {"name": "Наушники"},
    "watches": {"name": "Часы"},
    "tablets": {"name": "Планшеты"},
    "keyboards": {"name": "Клавиатуры"},
    "mice": {"name": "Мыши"},
    "monitors": {"name": "Мониторы"},
    "printers": {"name": "Принтеры"},
    "cameras": {"name": "Камеры"},
    "lenses": {"name": "Объективы"},
    "gaming-consoles": {"name": "Игровые приставки"},
    "games": {"name": "Игры"},
    "televisions": {"name": "Телевизоры"},
    "projectors": {"name": "Проекторы"},

    # Бытовая техника и уход
    "refrigerators": {"name": "Холодильники"},
    "stoves": {"name": "Плиты"},
    "microwaves": {"name": "Микроволновки"},
    "kettles": {"name": "Чайники"},
    "coffee-machines": {"name": "Кофемашины"},
    "blenders": {"name": "Блендеры"},
    "toasters": {"name": "Тостеры"},
    "vacuum-cleaners": {"name": "Пылесосы"},
    "irons": {"name": "Утюги"},
    "hair-dryers": {"name": "Фены"},
    "epilators": {"name": "Эпиляторы"},
    "shavers": {"name": "Бритвы"},
    "toothbrushes": {"name": "Зубные щетки"},
    "scales": {"name": "Весы"},
    "air-conditioners": {"name": "Кондиционеры"},

    # Одежда, обувь и аксессуары
    "dresses": {"name": "Платья"},
    "shirts": {"name": "Рубашки"},
    "jeans": {"name": "Джинсы"},
    "trousers": {"name": "Брюки"},
    "skirts": {"name": "Юбки"},
    "suits": {"name": "Костюмы"},
    "coats": {"name": "Пальто"},
    "jackets": {"name": "Куртки"},
    "sweaters": {"name": "Свитера"},
    "t-shirts": {"name": "Футболки"},
    "shorts": {"name": "Шорты"},
    "underwear": {"name": "Нижнее белье"},
    "socks": {"name": "Носки"},
    "sneakers": {"name": "Кроссовки"},
    "shoes": {"name": "Туфли"},
    "boots": {"name": "Ботинки"},
    "sandals": {"name": "Сандалии"},
    "bags": {"name": "Сумки"},
    "backpacks": {"name": "Рюкзаки"},
    "wallets": {"name": "Кошельки"},
    "belts": {"name": "Ремни"},
    "hats": {"name": "Шляпы"},
    "glasses": {"name": "Очки"},
    "earrings": {"name": "Серьги"},
    "rings": {"name": "Кольца"},
    "bracelets": {"name": "Браслеты"},

    # Мебель и домашний текстиль
    "beds": {"name": "Кровати"},
    "sofas": {"name": "Диваны"},
    "tables": {"name": "Столы"},
    "chairs": {"name": "Стулья"},
    "wardrobes": {"name": "Шкафы"},
    "dressers": {"name": "Комоды"},
    "shelves": {"name": "Полки"},
    "mirrors": {"name": "Зеркала"},
    "mattresses": {"name": "Матрасы"},
    "bed-linen": {"name": "Постельное белье"},
    "towels": {"name": "Полотенца"},
    "curtains": {"name": "Шторы"},
    "tableware": {"name": "Посуда"},
    "frying-pans": {"name": "Сковородки"},
    "pots": {"name": "Кастрюли"},
    "knives": {"name": "Ножи"},

    # Ремонт и инструменты
    "tools": {"name": "Инструменты"},
    "drills": {"name": "Дрели"},
    "screwdrivers": {"name": "Шуруповерты"},
    "hammers": {"name": "Молотки"},
    "wallpaper": {"name": "Обои"},
    "paints": {"name": "Краски"},
    "laminate": {"name": "Ламинат"},
    "tiles": {"name": "Плитка"},

    # Зоотовары
    "cat-food": {"name": "Корм для кошек"},
    "dog-food": {"name": "Корм для собак"},
    "aquariums": {"name": "Аквариумы"},
    "cages": {"name": "Клетки"},
    "pet-toys": {"name": "Игрушки для животных"},

    # Детские товары
    "baby-food": {"name": "Детское питание"},
    "diapers": {"name": "Подгузники"},
    "strollers": {"name": "Коляски"},
    "car-seats": {"name": "Автокресла"},
    "building-sets": {"name": "Конструкторы"},
    "dolls": {"name": "Куклы"},
    "toy-cars": {"name": "Машинки"},

    # Спорт и активный отдых
    "sportswear": {"name": "Спортивная одежда"},
    "balls": {"name": "Мячи"},
    "dumbbells": {"name": "Гантели"},
    "yoga": {"name": "Йога"},
    "tourism": {"name": "Туризм"},
    "tents": {"name": "Палатки"},
    "sleeping-bags": {"name": "Спальники"},
    "flashlights": {"name": "Фонари"},
}
for k in categories:
    categories[k]["id"] = str(uuid4())

# Маппинг родительских slug к списку дочерних категорий (value, slug)
parent_to_children = {
    "electronics-and-peripherals": [
        "smartphones",
        "laptops",
        "headphones",
        "watches",
        "tablets",
        "keyboards",
        "mice",
        "monitors",
        "printers",
        "cameras",
        "lenses",
        "gaming-consoles",
        "games",
        "televisions",
        "projectors",
    ],
    "home-appliances-and-personal-care": [
        "refrigerators",
        "stoves",
        "microwaves",
        "kettles",
        "coffee-machines",
        "blenders",
        "toasters",
        "vacuum-cleaners",
        "irons",
        "hair-dryers",
        "epilators",
        "shavers",
        "toothbrushes",
        "scales",
        "air-conditioners",
    ],
    "clothing-footwear-and-accessories": [
        "dresses",
        "shirts",
        "jeans",
        "trousers",
        "skirts",
        "suits",
        "coats",
        "jackets",
        "sweaters",
        "t-shirts",
        "shorts",
        "underwear",
        "socks",
        "sneakers",
        "shoes",
        "boots",
        "sandals",
        "bags",
        "backpacks",
        "wallets",
        "belts",
        "hats",
        "glasses",
        "earrings",
        "rings",
        "bracelets",
    ],
    "furniture-and-home-textiles": [
        "beds",
        "sofas",
        "tables",
        "chairs",
        "wardrobes",
        "dressers",
        "shelves",
        "mirrors",
        "mattresses",
        "bed-linen",
        "towels",
        "curtains",
        "tableware",
        "frying-pans",
        "pots",
        "knives",
    ],
    "repair-and-tools": [
        "tools",
        "drills",
        "screwdrivers",
        "hammers",
        "wallpaper",
        "paints",
        "laminate",
        "tiles",
    ],
    "pet-supplies": [
        "cat-food",
        "dog-food",
        "aquariums",
        "cages",
        "pet-toys",
    ],
    "baby-and-kids-products": [
        "baby-food",
        "diapers",
        "strollers",
        "car-seats",
        "building-sets",
        "dolls",
        "toy-cars",
    ],
    "sports-and-outdoors": [
        "sportswear",
        "balls",
        "dumbbells",
        "yoga",
        "tourism",
        "tents",
        "sleeping-bags",
        "flashlights",
    ],
}

child_to_parent = {}
for parent, children in parent_to_children.items():
    for child in children:
        child_to_parent[child] = parent

keywords_mapping = {
    "electronics-and-peripherals": ["электроника", "периферия", "гаджеты", "комплектующие", "компьютерные аксессуары"],
    "smartphones": ["телефон", "мобильник", "смарт", "айфон", "андроид"],
    "laptops": ["ноут", "компьютер портативный", "лэптоп", "macbook", "ноутбук для работы"],
    "headphones": ["гарнитура", "наушники беспроводные", "затычки", "airpods", "микрофон"],
    "watches": ["умные часы", "smart watch", "электронные часы", "apple watch", "фитнес браслет"],
    "tablets": ["планшет", "ipad", "планшет самсунг", "детский планшет"],
    "keyboards": ["клава", "клавиатура механическая", "клавиатура беспроводная", "игровая клавиатура"],
    "mice": ["мышка", "компьютерная мышь", "игровая мышь", "мышь беспроводная"],
    "monitors": ["экран", "дисплей", "монитор для компьютера", "игровой монитор"],
    "printers": ["принтер лазерный", "мфу", "струйный принтер", "картридж"],
    "cameras": ["фотоаппарат", "зеркалка", "беззеркалка", "экшн камера", "видеокамера"],
    "lenses": ["линза", "объектив камеры", "фикс объектив", "зум объектив"],
    "gaming-consoles": ["плойка", "playstation", "xbox", "nintendo switch", "игровая консоль"],
    "games": ["игровой диск", "компьютерные игры", "игры для приставок", "ключ активации"],
    "televisions": ["телек", "тв", "телевизор жк", "smart tv"],
    "projectors": ["проектор для дома", "кинопроектор", "экран для проектора"],
    "home-appliances-and-personal-care": ["техника для дома", "бытовая электроника", "уход за собой",
                                          "мелкая бытовая техника", "крупная бытовая техника"],
    "refrigerators": ["холодильник двухкамерный", "морозильник", "холодильник ноу фрост"],
    "stoves": ["газовая плита", "электрическая плита", "варочная панель", "духовка"],
    "microwaves": ["микроволновая печь", "свч"],
    "kettles": ["электрочайник", "термопот"],
    "coffee-machines": ["кофеварка", "кофемашина капсульная", "кофе в зернах"],
    "blenders": ["блендер погружной", "стационарный блендер"],
    "toasters": ["тостер для хлеба"],
    "vacuum-cleaners": ["пылесос робот", "моющий пылесос", "вертикальный пылесос"],
    "irons": ["утюг с парогенератором", "паровая станция"],
    "hair-dryers": ["фен для волос"],
    "epilators": ["эпилятор женский", "лазерный эпилятор"],
    "shavers": ["электробритва", "триммер"],
    "toothbrushes": ["электрическая зубная щетка", "ирригатор"],
    "scales": ["напольные весы", "кухонные весы"],
    "air-conditioners": ["сплит система", "кондиционер для дома"],
    "clothing-footwear-and-accessories": ["одежда", "обувь", "аксессуары", "мода", "стиль"],
    "dresses": ["женское платье", "вечернее платье"],
    "shirts": ["мужская рубашка", "женская блузка"],
    "jeans": ["мужские джинсы", "женские джинсы"],
    "trousers": ["штаны", "слаксы"],
    "skirts": ["юбка женская"],
    "suits": ["деловой костюм", "спортивный костюм"],
    "coats": ["зимнее пальто", "демисезонное пальто"],
    "jackets": ["пуховик", "ветровка", "кожаная куртка"],
    "sweaters": ["джемпер", "пуловер", "худи"],
    "t-shirts": ["майка", "поло"],
    "shorts": ["бермуды"],
    "underwear": ["трусы", "бюстгальтер", "белье"],
    "socks": ["гольфы", "чулки"],
    "sneakers": ["кеды", "спортивная обувь"],
    "shoes": ["лодочки", "женские туфли"],
    "boots": ["сапоги", "ботинки зимние"],
    "sandals": ["сандалии", "шлепанцы"],
    "bags": ["женская сумка", "клатч", "шоппер"],
    "backpacks": ["рюкзак городской", "школьный рюкзак"],
    "wallets": ["портмоне"],
    "belts": ["ремень", "пояс"],
    "hats": ["шапка", "кепка", "панама"],
    "glasses": ["солнцезащитные очки", "очки для зрения"],
    "earrings": ["сережки", "клипсы"],
    "rings": ["кольцо", "печатка"],
    "bracelets": ["браслет", "цепочка"],
    "furniture-and-home-textiles": ["мебель", "текстиль для дома", "интерьер", "дом и уют"],
    "beds": ["кровать двуспальная", "кровать односпальная"],
    "sofas": ["диван угловой", "диван раскладной", "тахта"],
    "tables": ["письменный стол", "обеденный стол", "журнальный столик"],
    "chairs": ["стул кухонный", "кресло", "компьютерное кресло"],
    "wardrobes": ["шкаф купе", "шкаф платяной"],
    "dressers": ["комод", "тумба"],
    "shelves": ["полка", "стеллаж"],
    "mirrors": ["зеркало в раме", "настенное зеркало"],
    "mattresses": ["матрас ортопедический", "наматрасник"],
    "bed-linen": ["простыня", "пододеяльник", "наволочка"],
    "towels": ["полотенце махровое", "банное полотенце"],
    "curtains": ["портьеры", "гардины", "жалюзи"],
    "tableware": ["тарелки", "чашки", "столовые приборы"],
    "frying-pans": ["сковорода антипригарная", "сковорода вок"],
    "pots": ["кастрюля", "ковш"],
    "knives": ["кухонный нож", "набор ножей"],
    "repair-and-tools": ["стройматериалы", "инструмент", "ремонт квартиры"],
    "tools": ["инструмент набор", "ручной инструмент"],
    "drills": ["дрель ударная", "перфоратор"],
    "screwdrivers": ["шуруповерт аккумуляторный"],
    "hammers": ["молоток", "киянка"],
    "wallpaper": ["обои для стен", "флизелиновые обои"],
    "paints": ["интерьерная краска", "фасадная краска"],
    "laminate": ["ламинат влагостойкий"],
    "tiles": ["керамогранит", "кафель"],
    "pet-supplies": ["товары для животных", "зоомагазин"],
    "cat-food": ["сухой корм для кошек", "влажный корм для кошек"],
    "dog-food": ["корм для собак", "сухой корм для собак"],
    "aquariums": ["аквариум с рыбками", "оборудование для аквариума"],
    "cages": ["клетка для птиц", "клетка для грызунов"],
    "pet-toys": ["игрушка для кошки", "игрушка для собаки"],
    "baby-and-kids-products": ["детские товары", "для детей", "магазин для детей"],
    "baby-food": ["смесь для новорожденных", "детское пюре"],
    "diapers": ["памперсы", "подгузники для детей"],
    "strollers": ["коляска люлька", "коляска трость"],
    "car-seats": ["детское автокресло", "бустер"],
    "building-sets": ["лего", "конструктор для детей"],
    "dolls": ["кукла барби", "пупс"],
    "toy-cars": ["машинка на радиоуправлении", "детские машинки"],
    "sports-and-outdoors": ["спорттовары", "туризм и отдых", "активный отдых"],
    "sportswear": ["спортивная форма", "спортивный костюм"],
    "balls": ["футбольный мяч", "баскетбольный мяч", "волейбольный мяч"],
    "dumbbells": ["гантели разборные", "гантели литые"],
    "yoga": ["коврик для йоги", "блок для йоги"],
    "tourism": ["туристическое снаряжение", "снаряжение для походов"],
    "tents": ["туристическая палатка", "палатка для кемпинга"],
    "sleeping-bags": ["спальный мешок", "термомешок"],
    "flashlights": ["налобный фонарь", "туристический фонарь"],
}

fixture_data = []

for category_slug, category in categories.items():
    obj = {
        **category,
        "parent_id": None,
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
        "is_active": True,

    }
    parent_slug = child_to_parent.get(category_slug)
    if parent_slug:
        obj["parent_id"] = categories[parent_slug]["id"]

    fixture_data.append({
        "model": "src.Category",
        "pk": obj["id"],
        "fields": obj
    })

# Сохраняем в JSON файл
with open('categories_fixture.json', 'w', encoding='utf-8') as f:
    json.dump(fixture_data, f, ensure_ascii=False, indent=2)
print(len(fixture_data), "записей")