# Generated by Django 6.0.3 on 2026-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('REJECTED', 'Rejected')], default='CREATED'),
        ),
    ]
