# Generated by Django 6.0.3 on 2026-05-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserveoperations',
            name='idempotency_key',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
