# Generated by Django 6.0.3 on 2026-04-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_remove_product_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
