# Generated by Django 6.0.3 on 2026-04-06 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_characteristic_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='src.product'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='src.sku'),
        ),
    ]
