# Generated by Django 6.0.3 on 2026-04-15 15:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_image_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.product')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
        ),
    ]
