# Generated by Django 6.0.3 on 2026-04-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_characteristic_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Characteristic',
        ),
    ]
