# Generated by Django 6.0.3 on 2026-05-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_reserveoperations_idempotency_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fullified_at',
            new_name='processed_at',
        ),
    ]
