# Generated by Django 6.0.3 on 2026-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_product_characteristics_sku_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skus/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_moderation', 'On moderation'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
    ]
