# Generated by Django 6.0.3 on 2026-04-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_invoice_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='src.invoice'),
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoices',
        ),
        migrations.AlterModelTable(
            name='invoiceitem',
            table='invoice_items',
        ),
    ]
