# Generated by Django 6.0.3 on 2026-05-02 10:49

import django.core.validators
import django.db.models.deletion
import src.validators.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_invoice_seller_alter_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sku_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='image',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='src.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=None, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_MODERATION', 'On Moderation'), ('MODERATED', 'Moderated'), ('BLOCKED', 'Blocked')], default='ON_MODERATION', max_length=20),
        ),
        migrations.AlterField(
            model_name='sku',
            name='active_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_image_order'),
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
        migrations.AddField(
            model_name='skuimage',
            name='SKU',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='src.sku'),
        ),
        migrations.AddConstraint(
            model_name='skuimage',
            constraint=models.UniqueConstraint(fields=('SKU', 'order'), name='unique_sku_image_order'),
        ),
    ]
