# Generated by Django 6.0.3 on 2026-05-03 09:51

import datetime
import django.core.validators
import django.db.models.deletion
import src.validators.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_invoice_seller_alter_invoiceitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('slug', models.CharField()),
                ('name', models.CharField()),
                ('type', models.CharField()),
                ('values', models.JSONField()),
            ],
            options={
                'db_table': 'categories_filters',
            },
        ),
        migrations.CreateModel(
            name='CategoryMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('tag', models.CharField()),
                ('value', models.CharField()),
            ],
            options={
                'db_table': 'categories_metatags',
            },
        ),
        migrations.CreateModel(
            name='CategorySEOKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('name', models.CharField()),
            ],
            options={
                'db_table': 'categories_keywords',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sku_images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ProductImage',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 12, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 12, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='src.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_MODERATION', 'On Moderation'), ('MODERATED', 'Moderated'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sku',
            name='active_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'order'), name='unique_product_image_order'),
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images',
        ),
        migrations.AddField(
            model_name='skuimage',
            name='sku',
            field=models.ForeignKey(db_column='sku_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='src.sku'),
        ),
        migrations.AddConstraint(
            model_name='skuimage',
            constraint=models.UniqueConstraint(fields=('sku', 'order'), name='unique_sku_image_order'),
        ),
    ]
