# Generated by Django 6.0.3 on 2026-05-02 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_categoryfilter_categoryseokeyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 12, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 12, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
