# Generated by Django 6.0.3 on 2026-05-02 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_skuimage_rename_image_productimage_remove_sku_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='cost_price',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='discount',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
