# Generated by Django 6.0.3 on 2026-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_categoryfilter_categorymetatag_categoryseokeyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
