# Generated by Django 6.0.3 on 2026-05-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_sku_cost_price_sku_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skuimage',
            old_name='SKU',
            new_name='sku',
        ),
    ]
