# Generated by Django 6.0.3 on 2026-05-03 06:57

import src.validators.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_category_created_at_category_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.UUIDField()),
                ('tag', models.CharField()),
                ('value', models.CharField()),
            ],
            options={
                'db_table': 'categories_metatags',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=None, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_MODERATION', 'On Moderation'), ('MODERATED', 'Moderated'), ('BLOCKED', 'Blocked')], default='ON_MODERATION', max_length=20),
        ),
    ]
