# Generated by Django 6.0.3 on 2026-05-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_product_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blocking_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
