# Generated by Django 6.0.3 on 2026-05-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0009_rename_sku_skuimage_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimage',
            name='sku',
            field=models.ForeignKey(db_column='sku_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='src.sku'),
        ),
    ]
