# Generated by Django 6.0.3 on 2026-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_skuimage_sku'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='skuimage',
            name='unique_sku_image_order',
        ),
        migrations.AddConstraint(
            model_name='skuimage',
            constraint=models.UniqueConstraint(fields=('sku', 'order'), name='unique_sku_image_order'),
        ),
    ]
