# Generated by Django 6.0.3 on 2026-05-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_product_field_reports_productfieldreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='field_reports',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productfieldreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_reports', to='src.product'),
        ),
    ]
