# Generated by Django 6.0.3 on 2026-05-09 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_product_field_reports_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='reserved_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
