# Generated by Django 6.0.3 on 2026-05-02 15:23

import django.core.validators
import src.validators.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_remove_skuimage_unique_sku_image_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=None, null=True, validators=[src.validators.main.validate_characteristics]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
