# Generated by Django 6.0.3 on 2026-05-09 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_sku_reserved_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveOperations',
            fields=[
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reserve_operations',
            },
        ),
    ]
