# Generated by Django 6.0.3 on 2026-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_alter_product_characteristics_alter_sku_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_MODERATION', 'On Moderation'), ('MODERATED', 'Moderated'), ('BLOCKED', 'Blocked'), ('HARD_BLOCKED', 'Hard Blocked')], default='CREATED', max_length=20),
        ),
    ]
