# Generated by Django 6.0.3 on 2026-05-10 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_reserveoperations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationDecisions',
            fields=[
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
