# Generated by Django 6.0.3 on 2026-05-12 07:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_moderationdecisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='characteristics',
        ),
        migrations.CreateModel(
            name='ProductCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.product')),
            ],
            options={
                'db_table': 'product_characteristics',
            },
        ),
        migrations.CreateModel(
            name='SkuCharacteristics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('sku_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sku')),
            ],
            options={
                'db_table': 'sku_characteristics',
            },
        ),
    ]
