# Generated by Django 6.0.3 on 2026-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_moderationdecisions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering', 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='skuimage',
            options={'ordering': ['ordering', 'created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='productimage',
            name='unique_product_image_order',
        ),
        migrations.RemoveConstraint(
            model_name='skuimage',
            name='unique_sku_image_order',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='value',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='order',
            new_name='ordering',
        ),
        migrations.RenameField(
            model_name='skuimage',
            old_name='order',
            new_name='ordering',
        ),
        migrations.AddField(
            model_name='product',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='skuimage',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(fields=('product', 'ordering'), name='unique_product_image_order'),
        ),
        migrations.AddConstraint(
            model_name='skuimage',
            constraint=models.UniqueConstraint(fields=('sku', 'ordering'), name='unique_sku_image_order'),
        ),
    ]
