# Generated by Django 6.0.3 on 2026-05-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0015_alter_productimage_options_alter_skuimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='skuimage',
            options={'ordering': ['ordering']},
        ),
    ]
