# Generated by Django 6.0.3 on 2026-05-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_alter_productimage_options_alter_skuimage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
    ]
