# Generated by Django 6.0.3 on 2026-05-14 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_remove_invoiceitem_product_invoice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='accepted_quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
