# Generated by Django 6.0.3 on 2026-05-14 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_rename_date_invoice_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullifiedOrders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fullified_orders',
            },
        ),
    ]
