# Generated by Django 6.0.3 on 2026-05-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0019_fullifiedorders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
    ]
