# Generated by Django 6.0.3 on 2026-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_blockingreason_product_moderator_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='moderator_comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterModelTable(
            name='blockingreason',
            table='blocking_reasons',
        ),
        migrations.AlterModelTable(
            name='moderationdecisions',
            table='moderation_decisions',
        ),
        migrations.AlterModelTable(
            name='productfieldreport',
            table='product_field_reports',
        ),
    ]
