# Generated by Django 6.0.3 on 2026-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0022_alter_product_moderator_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
