# Generated by Django 6.0.3 on 2026-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0024_sku_created_at_sku_stock_quantity_sku_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='article',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
