# Generated by Django 6.0.3 on 2026-05-23 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0027_order_orderitem_delete_fullifiedorders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterserviceOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue', models.CharField()),
                ('message', models.JSONField()),
            ],
            options={
                'db_table': 'interservice_outbox',
            },
        ),
    ]
